/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("jp.gr.java_conf.spica.wordle.java-application-conventions")
}

dependencies {
    implementation(project(":game"))
    implementation(project(":solver"))
}

application {
    // Define the main class for the application.
    mainClass.set("jp.gr.java_conf.spica.wordle.app.SystemIoApp")
}
tasks.named<JavaExec>("run") {
    standardInput = System.`in`
    standardOutput = System.`out`
}