/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("jp.gr.java_conf.spica.wordle.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
}

application {
    // Define the main class for the application.
    mainClass.set("jp.gr.java_conf.spica.wordle.app.App")
}
